### ISSUE TITLE
Move to voxpupuli namespace?

### ISSUE THREAD

**Issue by juniorsysadmin** [liamjbennett/puppet-win_facts#16]
Not speaking on behalf of anyone, but did you want to move this to the Voxpupuli namespace given that there are some modules in that namespace which have this module as as dependency?

If so follow the guidelines at https://voxpupuli.org/docs/ . Cheers!

**Comment by liamjbennett** [comment]
TBH I think this module should probably be killed off now in favor of using more up-to-date default faster facts.
